# Generated by Django 4.2.1 on 2023-05-14 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creationDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('deletionDate', models.DateField()),
                ('completion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creationDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('deletionDate', models.DateField()),
                ('content', models.TextField(max_length=250)),
                ('completion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('listid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.todolist')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
