# Generated by Django 4.2.1 on 2023-05-15 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deletionDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updateDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deletionDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updateDate',
            field=models.DateField(default=None),
        ),
    ]
