# Generated by Django 4.2.1 on 2023-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0002_remove_todoitem_name_alter_todoitem_creationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='deletionDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updateDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deletionDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updateDate',
            field=models.DateField(null=True),
        ),
    ]
