# Generated by Django 4.2.1 on 2023-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0003_alter_todoitem_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='deletionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='deletionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='updateDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
